extends: airbnb
rules:
    indent:
        - 2
        - 4
    no-else-return: 0
    quotes: 0
    no-alert: 0
    jsx-quotes: 0
    react/jsx-no-bind: 0
    react/jsx-indent-props:
        - 2
        - 4
    react/no-multi-comp: 0
    new-cap:
        - 2
        - capIsNewExceptions:
            - MathJax.Hub.Queue
            - KindEditor
            - Immutable.Range
            - Immutable.Repeat
            - Immutable.Map
            - Immutable.List
            - Immutable.Seq
            - Immutable.Record
    react/prop-types: 0
    no-console: 0
    arrow-body-style: 0
    func-names: 0
